import { ISupplierItem } from './supplier';
import { IProductItem } from './product';

export type IPurchaseStatus = 'pending' | 'completed' | 'cancelled';

/**
 * `offer`      - daily advice offer generated by the cron job (Bestel advies)
 * `offer_sent` - offer already sent to the supplier, never touched by the cron job
 * `purchase`   - booked purchase, stock has been added
 */
export type IPurchaseType = 'purchase' | 'offer' | 'offer_sent';

export type IPurchaseItem = {
    id: string;
    type?: IPurchaseType;
    purchase_invoice_date: string;
    purchase_invoice_number?: string;
    created_at: string;
    updated_at: string;
    supplier: number;
    supplier_detail: {
        id: number;
        name: string;
        supplier_code: string;
        logo?: string;
    };
    items: Array<{
        id: string;
        product: number;
        product_detail: {
            id: number;
            title: string;
            images: string[];
            ean: string;
        };
        product_quantity: number;
        product_purchase_price: string;
        vat_rate: number;
    }>;
    total_inc_btw: string;
    total_exc_btw: string;
    total_vat: string;
    sent_at?: string | null;
};

export type IPurchaseTableFilters = {
    name: string;
    status: string[];
    startDate: Date | null;
    endDate: Date | null;
};

export type IPurchaseTableFilterValue = string | string[] | Date | null; 